2019-07-13-12-48 [DubboServerHandler-172.16.201.15:20880-thread-2] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-12-48 [DubboServerHandler-172.16.201.15:20880-thread-3] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-12-48 [DubboServerHandler-172.16.201.15:20880-thread-4] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.auth.AuthServiceImpl.getUserPerms(Integer)
  2019-07-13-12-48 [DubboServerHandler-172.16.201.15:20880-thread-5] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-12-56 [DubboServerHandler-172.16.201.15:20880-thread-27] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-12-57 [DubboServerHandler-172.16.201.15:20880-thread-31] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-13-22 [DubboServerHandler-172.16.201.15:20880-thread-37] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-13-22 [DubboServerHandler-172.16.201.15:20880-thread-38] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-13-22 [DubboServerHandler-172.16.201.15:20880-thread-39] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.auth.AuthServiceImpl.getUserPerms(Integer)
  2019-07-13-13-22 [DubboServerHandler-172.16.201.15:20880-thread-40] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-13-23 [DubboServerHandler-172.16.201.15:20880-thread-53] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-13-24 [DubboServerHandler-172.16.201.15:20880-thread-60] [com.alibaba.dubbo.rpc.filter.ExceptionFilter] [ERROR] -  [DUBBO] Got unchecked and undeclared exception which called by 172.16.201.15. service: com.zhixiangmain.api.service.zjgl.zjxdgl.DisinfectionService, method: getPaginationData, exception: org.springframework.dao.RecoverableDataAccessException: 
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 51,754 milliseconds ago.  The last packet sent successfully to the server was 51,764 milliseconds ago.
### The error may exist in file [D:\zhixiangpingtaimain\zhixiangpingtai\zhixiang-service\target\classes\mapper\SiteMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select     p.id, p.name,p.pid pId, p.zindex, p.address, p.photo, p.lng, p.lat,p.sdid     from site p     LEFT JOIN site_siteRole rp ON rp.site_id=p.id     LEFT JOIN siteRole r ON r.id=rp.siteRole_id     LEFT JOIN user_siteRole ur ON ur.siteRole_id=r.id     WHERE ur.user_id=?     GROUP BY p.id     order by p.zindex
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 51,754 milliseconds ago.  The last packet sent successfully to the server was 51,764 milliseconds ago.
; Communications link failure

The last packet successfully received from the server was 51,754 milliseconds ago.  The last packet sent successfully to the server was 51,764 milliseconds ago.; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 51,754 milliseconds ago.  The last packet sent successfully to the server was 51,764 milliseconds ago., dubbo version: 2.5.5, current host: 127.0.0.1
  org.springframework.dao.RecoverableDataAccessException: 
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 51,754 milliseconds ago.  The last packet sent successfully to the server was 51,764 milliseconds ago.
### The error may exist in file [D:\zhixiangpingtaimain\zhixiangpingtai\zhixiang-service\target\classes\mapper\SiteMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select     p.id, p.name,p.pid pId, p.zindex, p.address, p.photo, p.lng, p.lat,p.sdid     from site p     LEFT JOIN site_siteRole rp ON rp.site_id=p.id     LEFT JOIN siteRole r ON r.id=rp.siteRole_id     LEFT JOIN user_siteRole ur ON ur.siteRole_id=r.id     WHERE ur.user_id=?     GROUP BY p.id     order by p.zindex
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 51,754 milliseconds ago.  The last packet sent successfully to the server was 51,764 milliseconds ago.
; Communications link failure

The last packet successfully received from the server was 51,754 milliseconds ago.  The last packet sent successfully to the server was 51,764 milliseconds ago.; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 51,754 milliseconds ago.  The last packet sent successfully to the server was 51,764 milliseconds ago.
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:100)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy101.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:139)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:76)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy127.findUserSites(Unknown Source)
	at com.zhixiangmain.impl.zjgl.zjxdgl.DisinfectionServiceImpl.getPaginationData(DisinfectionServiceImpl.java:303)
	at com.zhixiangmain.impl.zjgl.zjxdgl.DisinfectionServiceImpl$$FastClassBySpringCGLIB$$498a26c8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.zhixiangmain.impl.zjgl.zjxdgl.DisinfectionServiceImpl$$EnhancerBySpringCGLIB$$b97192f2.getPaginationData(<generated>)
	at com.alibaba.dubbo.common.bytecode.Wrapper76.invokeMethod(Wrapper76.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:61)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:102)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:98)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 51,754 milliseconds ago.  The last packet sent successfully to the server was 51,764 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:974)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:391)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
	at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy212.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at sun.reflect.GeneratedMethodAccessor288.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.github.pagehelper.SqlUtil._processPage(SqlUtil.java:351)
	at com.github.pagehelper.SqlUtil.processPage(SqlUtil.java:329)
	at com.github.pagehelper.PageHelper.intercept(PageHelper.java:150)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy210.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.GeneratedMethodAccessor304.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 44 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 51,754 milliseconds ago.  The last packet sent successfully to the server was 51,764 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:586)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:647)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:979)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1153)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:951)
	... 73 more
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
	at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:577)
	... 77 more
2019-07-13-13-24 [DubboServerHandler-172.16.201.15:20880-thread-54] [com.alibaba.dubbo.rpc.filter.ExceptionFilter] [ERROR] -  [DUBBO] Got unchecked and undeclared exception which called by 172.16.201.15. service: com.zhixiangmain.api.service.zhck.hwhsgl.HumitureService, method: getHumMonthBySdId, exception: org.springframework.dao.RecoverableDataAccessException: 
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 37,568 milliseconds ago.  The last packet sent successfully to the server was 37,585 milliseconds ago.
### The error may exist in file [D:\zhixiangpingtaimain\zhixiangpingtai\zhixiang-service\target\classes\mapper\HumitureMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT     COUNT(id) dataCount,     DATE_FORMAT( time, '%Y-%m-%d' ) createTime     FROM     temperature_data      WHERE  stat = ?                     AND DATE_FORMAT( time, '%Y%m' ) = ?       GROUP BY DATE_FORMAT(time, '%Y-%m-%d')
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 37,568 milliseconds ago.  The last packet sent successfully to the server was 37,585 milliseconds ago.
; Communications link failure

The last packet successfully received from the server was 37,568 milliseconds ago.  The last packet sent successfully to the server was 37,585 milliseconds ago.; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 37,568 milliseconds ago.  The last packet sent successfully to the server was 37,585 milliseconds ago., dubbo version: 2.5.5, current host: 127.0.0.1
  org.springframework.dao.RecoverableDataAccessException: 
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 37,568 milliseconds ago.  The last packet sent successfully to the server was 37,585 milliseconds ago.
### The error may exist in file [D:\zhixiangpingtaimain\zhixiangpingtai\zhixiang-service\target\classes\mapper\HumitureMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT     COUNT(id) dataCount,     DATE_FORMAT( time, '%Y-%m-%d' ) createTime     FROM     temperature_data      WHERE  stat = ?                     AND DATE_FORMAT( time, '%Y%m' ) = ?       GROUP BY DATE_FORMAT(time, '%Y-%m-%d')
### Cause: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 37,568 milliseconds ago.  The last packet sent successfully to the server was 37,585 milliseconds ago.
; Communications link failure

The last packet successfully received from the server was 37,568 milliseconds ago.  The last packet sent successfully to the server was 37,585 milliseconds ago.; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 37,568 milliseconds ago.  The last packet sent successfully to the server was 37,585 milliseconds ago.
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:100)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy101.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:139)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:76)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy203.findHumMonthBySdId(Unknown Source)
	at com.zhixiangmain.impl.zhck.hwhsgl.HumitureServiceImpl.getHumMonthBySdId(HumitureServiceImpl.java:223)
	at com.zhixiangmain.impl.zhck.hwhsgl.HumitureServiceImpl$$FastClassBySpringCGLIB$$1482908d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.zhixiangmain.impl.zhck.hwhsgl.HumitureServiceImpl$$EnhancerBySpringCGLIB$$97149361.getHumMonthBySdId(<generated>)
	at com.alibaba.dubbo.common.bytecode.Wrapper70.invokeMethod(Wrapper70.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:61)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:102)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:98)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 37,568 milliseconds ago.  The last packet sent successfully to the server was 37,585 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:974)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:391)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
	at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy212.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at sun.reflect.GeneratedMethodAccessor288.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.github.pagehelper.SqlUtil._processPage(SqlUtil.java:351)
	at com.github.pagehelper.SqlUtil.processPage(SqlUtil.java:329)
	at com.github.pagehelper.PageHelper.intercept(PageHelper.java:150)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy210.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.GeneratedMethodAccessor304.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 44 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 37,568 milliseconds ago.  The last packet sent successfully to the server was 37,585 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:555)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:725)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:664)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:979)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1153)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:951)
	... 73 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:107)
	at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:150)
	at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:180)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:549)
	... 78 more
2019-07-13-15-20 [DubboServerHandler-172.16.201.15:20880-thread-2] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-20 [DubboServerHandler-172.16.201.15:20880-thread-3] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-20 [DubboServerHandler-172.16.201.15:20880-thread-4] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.auth.AuthServiceImpl.getUserPerms(Integer)
  2019-07-13-15-20 [DubboServerHandler-172.16.201.15:20880-thread-5] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-22 [DubboServerHandler-172.16.201.15:20880-thread-15] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-22 [DubboServerHandler-172.16.201.15:20880-thread-16] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-23 [DubboServerHandler-172.16.201.15:20880-thread-17] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-23 [DubboServerHandler-172.16.201.15:20880-thread-18] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-23 [DubboServerHandler-172.16.201.15:20880-thread-19] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.auth.AuthServiceImpl.getUserPerms(Integer)
  2019-07-13-15-23 [DubboServerHandler-172.16.201.15:20880-thread-20] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-23 [DubboServerHandler-172.16.201.15:20880-thread-32] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-24 [DubboServerHandler-172.16.201.15:20880-thread-51] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-28 [DubboServerHandler-172.16.201.15:20880-thread-62] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-52 [DubboServerHandler-172.16.201.15:20880-thread-2] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-52 [DubboServerHandler-172.16.201.15:20880-thread-3] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-52 [DubboServerHandler-172.16.201.15:20880-thread-4] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.auth.AuthServiceImpl.getUserPerms(Integer)
  2019-07-13-15-52 [DubboServerHandler-172.16.201.15:20880-thread-5] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-53 [DubboServerHandler-172.16.201.15:20880-thread-17] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-55 [DubboServerHandler-172.16.201.15:20880-thread-29] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-56 [DubboServerHandler-172.16.201.15:20880-thread-32] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-56 [DubboServerHandler-172.16.201.15:20880-thread-33] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-56 [DubboServerHandler-172.16.201.15:20880-thread-34] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-56 [DubboServerHandler-172.16.201.15:20880-thread-35] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-56 [DubboServerHandler-172.16.201.15:20880-thread-36] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-56 [DubboServerHandler-172.16.201.15:20880-thread-37] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-38] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-39] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-40] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-49] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-48] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-47] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-46] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-45] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-44] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-43] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-42] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-41] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-50] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-51] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-53] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-52] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-54] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-55] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-56] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-57] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-57 [DubboServerHandler-172.16.201.15:20880-thread-58] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-58 [DubboServerHandler-172.16.201.15:20880-thread-59] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-58 [DubboServerHandler-172.16.201.15:20880-thread-60] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-58 [DubboServerHandler-172.16.201.15:20880-thread-61] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-58 [DubboServerHandler-172.16.201.15:20880-thread-62] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-58 [DubboServerHandler-172.16.201.15:20880-thread-63] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-58 [DubboServerHandler-172.16.201.15:20880-thread-64] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-58 [DubboServerHandler-172.16.201.15:20880-thread-65] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> User com.zhixiangmain.impl.user.UserServiceImpl.findUserByMobile(String)
  2019-07-13-15-58 [DubboServerHandler-172.16.201.15:20880-thread-66] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.auth.AuthServiceImpl.getUserPerms(Integer)
  2019-07-13-15-58 [DubboServerHandler-172.16.201.15:20880-thread-67] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-58 [DubboServerHandler-172.16.201.15:20880-thread-78] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-59 [DubboServerHandler-172.16.201.15:20880-thread-80] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-59 [DubboServerHandler-172.16.201.15:20880-thread-79] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-15-59 [DubboServerHandler-172.16.201.15:20880-thread-82] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-16-00 [DubboServerHandler-172.16.201.15:20880-thread-84] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  2019-07-13-16-00 [DubboServerHandler-172.16.201.15:20880-thread-86] [com.zhixiangmain.config.DynamicDattaSourceAspect] [ERROR] - 数据源 default 不存在使用默认的数据源 -> List com.zhixiangmain.impl.site.SiteServiceImpl.getUserSites(Integer)
  